### ISSUE TITLE
the hashrate seems a bit low on rx 550 4g.

### ISSUE THREAD

**Issue by caowenyu75** [Lolliedieb/lolMiner-preview#10]
is it possible to do some optimization? for eth, it's about half of rx 470. but only around 40% for beam.

another thing is the support for crimson driver.

**Comment by Lolliedieb** [comment]
Hopefully fixed with alpha 2, plz test and report back :)

**Comment by caowenyu75** [comment]
rx 570, 470 improved. ty so much. rx 550, 560, still bad. around 3sol/sec. Please check. TYI

**Comment by caowenyu75** [comment]
now I can get around 60 sol/sec on a 6 card rx 470 rig. but for a 12 card rx 550 and rx 560, it's only around 38-40 sol/sec.

**Comment by Lolliedieb** [comment]
The speeds for the 470/570 look normal, but I fear for 560 and 550, too

570 has 32 shader cluster with 228 GB/s mem bandwidth
560 has 14 or 16 shader cluster with 112 GB/s mem bandwidth and
550 is cut down to 8 or 10 clusters with 96 GB/s bandwidth.

So I do not expect a 560 to exceed maybe 4-5 sol/s and a 550 should do 3-4, but maybe even only 2-3. My iGPU with same number of shaders, little lesser clocked and 1/4 of mem bandwidth does 0.5, so here maybe 2.5 for the 550.

Its just the hardware is stripped down so far from 570/580.

**Comment by caowenyu75** [comment]
ok, for eth mining, 12 card 550 and 560 rig got around the same hashrate with 6 card 470 rig. so, i expected the same for equilhash.
