### ISSUE TITLE
how to specify device whose index is greater than 9.

### ISSUE THREAD

**Issue by caowenyu75** [Lolliedieb/lolMiner-preview#12]
for mining rigs with more than 10 GPUs, I found the device control option cannot control the device with an index greater than 9. I tried 10, 11, but it does not work. Please check and advice.

TYI

**Comment by Lolliedieb** [comment]
Usually doing --devices 8,9,10,11,12 should just work. If not in config file
"DEVICES" : [8,9,10,11,12],
works fine
