### ISSUE TITLE
The miner keeps mining on fail-over pool

### ISSUE THREAD

**Issue by cdarken** [Lolliedieb/lolMiner-preview#16]
After the miner switches the the fail-over pool it should check periodically if the main pool is available and switch back to it.

**Comment by zorzgeo** [comment]
@cdarken Read carefully .pdf manual in Lol miners unzipped folder ;) 

> "DEFAULTS" : {
		"DEVICES" : "AMD",
		"CONNECTATTEMPTS" : 5,
		"WAITFORREWIND" : 3,
		"LOGS" : 1,  	
		"APIPORT" : 0
	},
This is my DFAULTS set in .json file. Starting, miner 1st caal DEFAULTS and after that all written in .json...
Read .pdf file for explanation.
