### ISSUE TITLE
Add support for mining BEAM on NiceHash

### ISSUE THREAD

**Issue by t4nja** [Lolliedieb/lolMiner-preview#18]
NiceHash requires a change in stratum protocol for mining BEAM. Job message contains additional parameter "nonceprefix", which follows the same rules as "nonceprefix" field in the login response. 

Protocol specifications: 
https://github.com/nicehash/Specifications/blob/master/Beam_NiceHash_v1.0.txt

**Comment by suxxer1** [comment]
+1

**Comment by Viper70** [comment]
+1
Not connect to NiceHash
"Handshake failed with message stream truncated"

**Comment by mitagmio** [comment]
+1 
Error: Handshake failed with message stream truncated

**Comment by RealFlex** [comment]
+1

**Comment by Lolliedieb** [comment]
Closes long time ago, lolMiner is full nicehash compatible in all release versions
https://github.com/Lolliedieb/lolMiner-releases
