### ISSUE TITLE
AMD rx 460 & rx 550 algo equi192_7 not supported !

### ISSUE THREAD

**Issue by AbdelXY** [Lolliedieb/lolMiner-preview#2]
Hi,
I was setting up to mining some equihash coins like equi 144_5 (works great) but unfortunately It does not work for equishash 192_7 algo as I get an error saying:
**"RX 460 and RX 550 are not supported for the current algo"**

I was trying to find a solution but nothing.
Please may you look at it and try to fix it.
I enjoy your work and thank you

**Comment by Lolliedieb** [comment]
Hi there, 
can you give me an a screen of clinfo.exe (comes with AMD drivers) of those cards? Usually the compatibility check fails due to some device limitations I can best see there.

**Comment by AbdelXY** [comment]
Hi there,
I will upload it here, 
find the clinfo.exe files below
[Number of platforms.docx](https://github.com/Lolliedieb/lolMiner-preview/files/2608712/Number.of.platforms.docx)

**Comment by Lolliedieb** [comment]
Ok, the reason for this not to work is that those are 2G cards (Global memory size:                            2147483648 - the number is bytes) and 192/7 currently needs at least ~3G. Therefore these cards can not mine 192/7. With a bit luck and no screen attached they may be able to mine 144/5 (using 1.85G) or else AION (1G), but Zero & GenX will be difficult with less then 3G.

**Comment by AbdelXY** [comment]
really?!
So if my amd 460 and 550 were more than 2G then 192/7 would work.
**Many thanks and 144/5 works great btw.**
Also
**Will 96/5 works????????????**

**Comment by Lolliedieb** [comment]
Yes, 96/5 will works in alpha 3 and up :)
Hope to have a boost for it with alpha 4 ;)

Am Do., 22. Nov. 2018, 17:14 hat AbdelXY <notifications@github.com>
geschrieben:

**Comment by AbdelXY** [comment]
I appreciate your hard work and keep it going.
Many thanks for the miner and your reply
