### ISSUE TITLE
algorithm performance and gminer

### ISSUE THREAD

**Issue by adminnu** [Lolliedieb/lolMiner-preview#29]
https://bitcointalk.org/index.php?topic=5034735.0 blog claims that they stole your algorithm, but when I run their applications, I get a 150 Sol / s card on five 1080ti cards in their program, and you have only 120 Sol / s how so?

**Comment by Lolliedieb** [comment]
Well it was about amd codes - not Nvidia ;)
But over a year ago and thus history
