### ISSUE TITLE
Error on Ubuntu 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'

### ISSUE THREAD

**Issue by shrewdacumen** [Lolliedieb/lolMiner-preview#4]
After several hours of running lolMiner 0.6 alpha 2 on Linux(Ubuntu.)
I got the following message:
"terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  cancel: Bad file descriptor"

**Comment by Lolliedieb** [comment]
The error may occur when the config file is not found or when all GPUs fail the compatibility check. Can you share the full output and your command line parameters you use to start the miner?

**Comment by Lolliedieb** [comment]
Should be fixed in 0.7 trunk
