### ISSUE TITLE
Strange GPU enumeration

### ISSUE THREAD

**Issue by angelbbs** [Lolliedieb/lolMiner-preview#6]
Is it possible to add options to disable detections AMD or NVIDIA GPUs? I.e. --noamd and --nonvidia. This is necessary for proper integration into NiceHash Miner Legacy Fork Fix

**Comment by Lolliedieb** [comment]
At the moment not supported, but will come back with alpha 3 or alpha 4.
Also will sort the GPUs by their bus address then :)

**Comment by Lolliedieb** [comment]
Closed with alpha 3/4.
lolMiner now understands --devices AMD and --devices NVIDIA and sorts the devices by their PCIE bus address as e.g. Nvidia SMI does
