### ISSUE TITLE
Miner fails to use all 6 cards at the same time

### ISSUE THREAD

**Issue by slavko989** [Lolliedieb/lolMiner-preview#9]
There is a problem with using all cards in multi-gpu setups, for example, 5 cards do just fine throwing 8-9 sol and the sixth fails at all time, throwing just 2-3sols. Even lowering clocks drastically does nothing.

**Comment by PriceTT** [comment]
Similar problem with version B for 4 x ROG-STRIX-RX570-O4G-GAMING
1 -3 of the cards will be at 8-10 sol wile the others are at 1-2 sol (every time i restart the miner it changes)

**Comment by Lolliedieb** [comment]
Hopefully fixed with alpha 2, plz test and report back :)

**Comment by slavko989** [comment]
I am happy to confirm that the problem has been solved. Good job on the speeds too Lolliedieb!
